import datetime

dct = {
    "Table": {
        "Name": "parquet_example_has_partition",
        "DatabaseName": "glue_crawler_test",
        "Owner": "owner",
        "CreateTime": datetime.datetime(2024, 8, 30, 9, 29, 39, tzinfo=tzlocal()),
        "UpdateTime": datetime.datetime(2024, 8, 30, 9, 29, 39, tzinfo=tzlocal()),
        "LastAccessTime": datetime.datetime(2024, 8, 30, 9, 29, 39, tzinfo=tzlocal()),
        "Retention": 0,
        "StorageDescriptor": {
            "Columns": [
                {"Name": "id", "Type": "bigint"},
                {"Name": "name", "Type": "string"},
                {"Name": "create_time", "Type": "timestamp"},
            ],
            "Location": "s3://bmt-app-dev-us-east-1-data/projects/learn_aws/glue_crawler/databases/glue_crawler_test/parquet_example_has_partition/",
            "InputFormat": "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat",
            "OutputFormat": "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat",
            "Compressed": False,
            "NumberOfBuckets": -1,
            "SerdeInfo": {
                "SerializationLibrary": "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe",
                "Parameters": {"serialization.format": "1"},
            },
            "BucketColumns": [],
            "SortColumns": [],
            "Parameters": {
                "sizeKey": "74604",
                "objectCount": "10",
                "UPDATED_BY_CRAWLER": "glue_crawler_test__parquet_example_has_partition",
                "recordCount": "1000",
                "CrawlerSchemaSerializerVersion": "1.0",
                "averageRecordSize": "103",
                "partition_filtering.enabled": "true",
                "compressionType": "none",
                "CrawlerSchemaDeserializerVersion": "1.0",
                "classification": "parquet",
                "typeOfData": "file",
            },
            "StoredAsSubDirectories": False,
        },
        "PartitionKeys": [{"Name": "year", "Type": "string"}],
        "TableType": "EXTERNAL_TABLE",
        "Parameters": {
            "sizeKey": "74604",
            "objectCount": "10",
            "UPDATED_BY_CRAWLER": "glue_crawler_test__parquet_example_has_partition",
            "recordCount": "1000",
            "CrawlerSchemaSerializerVersion": "1.0",
            "averageRecordSize": "103",
            "partition_filtering.enabled": "true",
            "compressionType": "none",
            "CrawlerSchemaDeserializerVersion": "1.0",
            "classification": "parquet",
            "typeOfData": "file",
        },
        "CreatedBy": "arn:aws:sts::878625312159:assumed-role/all-services-admin-role/AWS-Crawler",
        "IsRegisteredWithLakeFormation": False,
        "CatalogId": "878625312159",
        "VersionId": "1",
    },
}
